[2022-10-11 04:22:45.244] [remoteagent] [info] Extension host agent started.
[2022-10-11 04:22:45.476] [remoteagent] [info] [127.0.0.1][dbf86dd0][ManagementConnection] New connection established.
[2022-10-11 04:22:45.512] [remoteagent] [info] [127.0.0.1][ea77403a][ExtensionHostConnection] New connection established.
[2022-10-11 04:22:45.519] [remoteagent] [info] [127.0.0.1][ea77403a][ExtensionHostConnection] <2118> Launched Extension Host Process.
[2022-10-11 04:22:50.190] [remoteagent] [info] [127.0.0.1][dbf86dd0][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-10-11 04:22:50.207] [remoteagent] [info] [127.0.0.1][ea77403a][ExtensionHostConnection] <2118> Extension Host Process exited with code: 0, signal: null.
[2022-10-11 04:22:50.208] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-10-11 04:22:56.959] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-10-11 04:22:56.959] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-10-11 04:22:57.079] [remoteagent] [info] [127.0.0.1][0121c877][ManagementConnection] New connection established.
[2022-10-11 04:22:57.098] [remoteagent] [info] [127.0.0.1][341c62cc][ExtensionHostConnection] New connection established.
[2022-10-11 04:22:57.103] [remoteagent] [info] [127.0.0.1][341c62cc][ExtensionHostConnection] <2277> Launched Extension Host Process.
[2022-10-11 04:22:59.433] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateTitle (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:2984)","    at Object.call (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-11 04:24:21.066] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:3001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 04:24:21.309] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:3001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 04:27:56.961] [remoteagent] [info] New EH opened, aborting shutdown
[2022-10-11 05:16:25.828] [remoteagent] [info] [127.0.0.1][0121c877][ManagementConnection] The client has reconnected.
[2022-10-11 05:16:26.854] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateIcon (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:3046)","    at Object.call (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-11 05:16:26.854] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateTitle (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:2984)","    at Object.call (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-11 05:16:26.854] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateTitle (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:2984)","    at Object.call (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-11 05:16:27.399] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateTitle (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:2984)","    at Object.call (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-11 05:16:29.349] [remoteagent] [info] [127.0.0.1][341c62cc][ExtensionHostConnection] The client has reconnected.
[2022-10-11 05:48:33.203] [remoteagent] [info] [127.0.0.1][1b8c8129][ManagementConnection] New connection established.
[2022-10-11 05:48:33.223] [remoteagent] [info] [127.0.0.1][4017f200][ExtensionHostConnection] New connection established.
[2022-10-11 05:48:33.230] [remoteagent] [info] [127.0.0.1][4017f200][ExtensionHostConnection] <4199> Launched Extension Host Process.
[2022-10-11 05:48:34.891] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateTitle (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:2984)","    at Object.call (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-11 05:48:40.350] [remoteagent] [info] [127.0.0.1][1b8c8129][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-10-11 05:48:42.186] [remoteagent] [info] [127.0.0.1][4017f200][ExtensionHostConnection] <4199> Extension Host Process exited with code: 0, signal: null.
[2022-10-11 05:48:46.456] [remoteagent] [info] [127.0.0.1][b767788a][ManagementConnection] New connection established.
[2022-10-11 05:48:46.499] [remoteagent] [info] [127.0.0.1][8150fd21][ExtensionHostConnection] New connection established.
[2022-10-11 05:48:46.508] [remoteagent] [info] [127.0.0.1][8150fd21][ExtensionHostConnection] <4358> Launched Extension Host Process.
[2022-10-11 05:53:33.463] [remoteagent] [info] [127.0.0.1][341c62cc][ExtensionHostConnection] <2277> Extension Host Process exited with code: 0, signal: null.
[2022-10-11 06:22:52.769] [remoteagent] [info] [127.0.0.1][ea6cd88c][ManagementConnection] New connection established.
[2022-10-11 06:22:52.808] [remoteagent] [info] [127.0.0.1][80313bd7][ExtensionHostConnection] New connection established.
[2022-10-11 06:22:52.818] [remoteagent] [info] [127.0.0.1][80313bd7][ExtensionHostConnection] <11685> Launched Extension Host Process.
[2022-10-11 06:22:57.294] [remoteagent] [info] [127.0.0.1][ea6cd88c][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-10-11 06:22:57.313] [remoteagent] [info] [127.0.0.1][80313bd7][ExtensionHostConnection] <11685> Extension Host Process exited with code: 0, signal: null.
[2022-10-11 06:23:04.338] [remoteagent] [info] [127.0.0.1][699a8d1a][ManagementConnection] New connection established.
[2022-10-11 06:23:04.377] [remoteagent] [info] [127.0.0.1][a290cf0a][ExtensionHostConnection] New connection established.
[2022-10-11 06:23:04.387] [remoteagent] [info] [127.0.0.1][a290cf0a][ExtensionHostConnection] <11844> Launched Extension Host Process.
[2022-10-11 06:23:06.792] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateTitle (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:2984)","    at Object.call (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-11 06:41:44.559] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:49379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 06:41:44.560] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:49379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 06:42:48.774] [remoteagent] [info] [127.0.0.1][b767788a][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-10-11 06:42:48.815] [remoteagent] [info] [127.0.0.1][8150fd21][ExtensionHostConnection] <4358> Extension Host Process exited with code: 0, signal: null.
[2022-10-11 06:42:52.370] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:49404
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 06:42:52.371] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:49404
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 07:16:39.920] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 07:16:39.921] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 07:16:40.183] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 07:16:55.106] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 07:16:55.106] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 07:16:55.377] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 07:18:28.345] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:49379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 07:18:28.345] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:49379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 07:18:38.792] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:49404
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 07:18:43.893] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:49379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 07:18:46.263] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:49379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 12:02:22.312] [remoteagent] [info] [127.0.0.1][a290cf0a][ExtensionHostConnection] <11844> Extension Host Process exited with code: 0, signal: null.
[2022-10-11 12:02:22.312] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-10-11 12:07:22.314] [remoteagent] [info] Last EH closed, shutting down
