[2022-10-11 14:24:47.100] [remoteagent] [info] Extension host agent started.
[2022-10-11 14:24:47.342] [remoteagent] [error] [127.0.0.1][699a8d1a][ManagementConnection] Unknown reconnection token (never seen).
[2022-10-11 14:24:54.059] [remoteagent] [info] [127.0.0.1][98aa2105][ManagementConnection] New connection established.
[2022-10-11 14:24:54.199] [remoteagent] [info] [127.0.0.1][d1395929][ExtensionHostConnection] New connection established.
[2022-10-11 14:24:54.207] [remoteagent] [info] [127.0.0.1][d1395929][ExtensionHostConnection] <104240> Launched Extension Host Process.
[2022-10-11 14:24:57.714] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateTitle (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:2984)","    at Object.call (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/home/ubuntu/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-11 14:24:58.513] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:49379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 14:32:49.689] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:3001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 14:32:49.946] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:3001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-11 15:01:08.574] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/ubuntu)
[2022-10-11 15:01:08.574] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
[2022-10-11 18:46:00.094] [remoteagent] [info] [127.0.0.1][d1395929][ExtensionHostConnection] <104240> Extension Host Process exited with code: 0, signal: null.
[2022-10-11 18:46:00.095] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-10-11 18:51:00.095] [remoteagent] [info] Last EH closed, shutting down
